### ISSUE TITLE
[BUG-REPORT] Vaex cannot open more than 816 parquet files on s3

### ISSUE THREAD

**Issue by aburkov** [vaexio/vaex#1084]
**Description**

I try to open many parquet partitions. Vaex opens first 816, then fails with the following error:

> ERROR:MainThread:vaex:error opening 's3://my/path/part-00817-db9aee77-5b44-4571-857b-ea2879609450.c000.snappy.parquet'
> Traceback (most recent call last):
>   File "/home/myuser/p/VS_Code_Projects/SkillExtractor/test_vaex_multiprocessing.py", line 32, in <module>
>     df = vaex.concat([df, vaex.open(parquet_file)])
>   File "/home/myuser/anaconda3/lib/python3.8/site-packages/vaex/__init__.py", line 211, in open
>     ds = vaex.dataset.open(path, fs_options=fs_options, *args, **kwargs)
>   File "/home/myuser/anaconda3/lib/python3.8/site-packages/vaex/dataset.py", line 42, in open
>     return opener.open(path, *args, **kwargs)
>   File "/home/myuser/anaconda3/lib/python3.8/site-packages/vaex/arrow/opener.py", line 29, in open
>     return open_parquet(path, *args, **kwargs)
>   File "/home/myuser/anaconda3/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 175, in open_parquet
>     arrow_ds = pyarrow.dataset.dataset(path, filesystem=file_system)
>   File "/home/myuser/anaconda3/lib/python3.8/site-packages/pyarrow/dataset.py", line 671, in dataset
>     return _filesystem_dataset(source, **kwargs)
>   File "/home/myuser/anaconda3/lib/python3.8/site-packages/pyarrow/dataset.py", line 428, in _filesystem_dataset
>     fs, paths_or_selector = _ensure_single_source(source, filesystem)
>   File "/home/myuser/anaconda3/lib/python3.8/site-packages/pyarrow/dataset.py", line 395, in _ensure_single_source
>     file_info = filesystem.get_file_info([path])[0]
>   File "pyarrow/_fs.pyx", line 434, in pyarrow._fs.FileSystem.get_file_info
>   File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
>   File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
> OSError: When getting information for key 'demand/positions-20211123/place_country_code=US/part-00817-db9aee77-5b44-4571-857b-ea2879609450.c000.snappy.parquet' in bucket 'tn-datafeed-dev': AWS Error [code 99]: curlCode: 6, Couldn't resolve host name

Tried to open in two different ways, in both cases the same error.

Way 1:

`df = vaex.open("s3://some/path/*.parquet")`

Way 2:

```
s3 = boto3.resource('s3')
my_bucket = s3.Bucket('my_bucket_name')

parquet_files = []
for my_bucket_object in my_bucket.objects.filter(Prefix='some/prefix'):
    if my_bucket_object.key.endswith(".parquet"):
        parquet_files.append("s3://" + my_bucket._name + "/" + my_bucket_object.key)

df = None
for parquet_file in parquet_files:
    if not df:
        df = vaex.open(parquet_file)
    else:
        try:
            df = vaex.concat([df, vaex.open(parquet_file)])
        except Exception as e:
            print(f"WARNING: The file {parquet_file} could not be read!")
            print(e)
```

Everything is fine until it reaches 816 files open. I tried to start with parquet # 817 and it works until another certain number of files is open.

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: {'vaex-core': '4.0.0a5'}
 - Vaex was installed via: pip
 - OS: AWS Linux v2

**Comment by maartenbreddels** [comment]
Are you on EC2 and in the same region as the bucket (that might help me reproduce it)

**Comment by maartenbreddels** [comment]
Being in the same region did not matter, I managed to reproduce it. It seems that for some reason the underlying library curl has some issues, caching the region resolving and filesystem object (which is a good idea anyway), avoid the issue. I'll let you know when #1085 is released.
Thanks for reporting, would have never found this out otherwise.

**Comment by maartenbreddels** [comment]
Fixed in the latest release:
```
pip install vaex-core==4.0.0a10
or
pip install vaex==4.0.0a5
```

**Comment by Hasna1994** [comment]
Hi, I'm still having this issue with vaex versions:
{'vaex': '4.9.0',
 'vaex-core': '4.9.0',
 'vaex-viz': '0.5.1',
 'vaex-hdf5': '0.12.1',
 'vaex-server': '0.8.1',
 'vaex-astro': '0.9.1',
 'vaex-jupyter': '0.7.0',
 'vaex-ml': '0.17.0'}

**Comment by maartenbreddels** [comment]
Do you get the same error: ' Couldn't resolve host name' ?

**Comment by Hasna1994** [comment]
I restarted my kernel and it worked. I might have had my VPN turned on but its working now. However, when I try to do `df.export_parquet(path='s3://..etc',fs_options={})` I get the error:
`OSError: When initiating multiple part upload for key 'parquetfileslarge/df.parquet' in bucket '<bucket>': AWS Error [code 99]: curlCode: 28, Timeout was reached
`
I even tried with 5 rows of a df to see if it was a size issue but it wasn't.

**Comment by maartenbreddels** [comment]
This means it is (probably) not related, if it persistent, please open a new issue.
