### ISSUE TITLE
vaex.example() is broken

### ISSUE THREAD

**Issue by teake** [vaexio/vaex#169]
`vaex.example()` is doesn't work because http://vaex.astro.rug.nl/data/helmi-dezeeuw-2000-10p.hdf5 returns a 403 (at the time of writing). This is with `vaex` 1.0.0b7 and `vaex-core` 0.6.1 from conda-forge.

**Comment by maartenbreddels** [comment]
Hi Teake,

thanks for letting me know, it seems the machine at Kapteyn that has this file is offline. I'll try to see if it can be put online.

cheers,

Maarten

**Comment by alimcmaster1** [comment]
Could potentially see if we can store these in s3 - so we don't have to worry about this kind of thing. What do you think @maartenbreddels ?

**Comment by maartenbreddels** [comment]
Yes, that is a great idea! After #267 is merged, we can fully depend on s3, also for larger datasets, since it will only download what is needed.

**Comment by alimcmaster1** [comment]
Awesome thanks! 

This might be a nice issue for a newcomer like me to work on! Once the below is merged I’m happy to take a look at copying the data across to s3 and updating the relevant code in .example()

**Comment by maartenbreddels** [comment]
Great, see https://github.com/vaexio/vaex/blob/master/tests/s3_test.py for the usage.

**Comment by r-a-i** [comment]
Hi, I just ran into this 403 error trying to run df = vaex.example() with a fresh install of vaex and jupyter lab (via conda). Was this ever fixed?

**Comment by maartenbreddels** [comment]
Yeah, we noticed, it was fixed, but @JovanVeljanoski is setting up a more permanent solution now

**Comment by JovanVeljanoski** [comment]
Hi @teake @alimcmaster1 @r-a-i 

This issue will be fixed in the next release of vaex.
For now, you will need to manually update link pointing to the example dataset. You can do that like this:
```
import vaex

vaex.datasets.helmi_de_zeeuw_10percent.url = 'https://github.com/vaexio/vaex-datasets/raw/master/datasets/helmi-dezeeuw-2000-10p.hdf5'

df = vaex.example()  # this will now work
```

This needs to be done only once per user or machine, since the data will be cached locally.
You can also download the dataset manually using the link in the code-block above (as it is now hosted on github).

Cheers

**Comment by majkelx** [comment]
One year later it's still broken. Which means most of tutorials are broken.

**Comment by maartenbreddels** [comment]
Hi Mikołaj,

it is broken *again*, not still. The workaround (til we release the next version) is posted by Jovan.

cheers,

Maarten

**Comment by Codeguyross** [comment]
> Hi @teake @alimcmaster1 @r-a-i
> 
> This issue will be fixed in the next release of vaex.
> For now, you will need to manually update link pointing to the example dataset. You can do that like this:
> 
> ```
> import vaex
> 
> vaex.datasets.helmi_de_zeeuw_10percent.url = 'https://github.com/vaexio/vaex-datasets/raw/master/datasets/helmi-dezeeuw-2000-10p.hdf5'
> 
> df = vaex.example()  # this will now work
> ```
> 
> This needs to be done only once per user or machine, since the data will be cached locally.
> You can also download the dataset manually using the link in the code-block above (as it is now hosted on github).
> 
> Cheers

If anyone comes in and tries this example it still doesnt work by loading the file as seen in the above accepted answer. However, the link does work. Put in 'https://github.com/vaexio/vaex-datasets/raw/master/datasets/helmi-dezeeuw-2000-10p.hdf5' into your browser and it will download the file. Put a data file in the vaex example project where the notebook is located and add in the downloaded file. Then use the following command to load the data instead of `ds = vx.example()`. 

`ds = vx.open('data/helmi-dezeeuw-2000-10p.hdf5') # in case you want to load a different dataset`

**Comment by JovanVeljanoski** [comment]
Hi @Codeguyross 

I just tried this last night on google colab - fresh install and calling vaex.example() it worked fine..
do you have the latest version installed?

**Comment by Codeguyross** [comment]
> Hi @Codeguyross
> 
> I just tried this last night on google colab - fresh install and calling vaex.example() it worked fine..
> do you have the latest version installed?

I just downloaded it today with conda install.  I suppose it is possible that something was blocking the download and it it seems to be working now. I tried for a while this morning and it kept saying failed to download but I wasnt having network issues but the direct download of the file worked. I do have any ideas on why it wasnt working
