### ISSUE TITLE
[FEATURE-REQUEST] Could we have `str.rsplit()`?

### ISSUE THREAD

**Issue by yohplala** [vaexio/vaex#1697]
**Description**
Hi,
`str.split()` is supported by vaex, but trying to use `str.rsplit()` returns an error.

```python
import vaex as vx
li = ['ah.1.arrow', 'ah.199.arrow', 'ah.79.arrow']
vdf = vx.from_arrays(fname = li)
vdf['ts'] = vdf['fname'].str.rsplit('.',1).apply(lambda x: x[-2])
```
Error is triggered when trying to display `vdf`.
```python
vdf
ERROR:MainThread:vaex:error evaluating: ts at rows 0-3
KeyError: 'Unknown variables or column: "lambda_function(str_rsplit(fname, \'.\', 1))"'
Out[54]: 
  #  fname         ts
  0  ah.1.arrow    error
  1  ah.199.arrow  error
  2  ah.79.arrow   error
```
But with `split()`, it works.

**Additional context**
Strings I want to process are file path (basepath + basename), but information that is of interest is at the end. Using `rsplit('.',1)` ought to be faster than splitting the full string with `split()`.

**Comment by JovanVeljanoski** [comment]
This is a bug in arrow i think - which was fixed. Please update your `pyarrow`. I just tried with pyarrow==6.0.0 and rsplit works fine.

**Comment by yohplala** [comment]
> This is a bug in arrow i think - which was fixed. Please update your `pyarrow`. I just tried with pyarrow==6.0.0 and rsplit works fine.

Hi,
May it be that you also solved something into last vaex version?
I upgraded to pyarrow 6.0.0 and I still have an error message (but not the same).

Here are the versions I am using for vaex:
{'vaex': '4.5.0',
 'vaex-core': '4.5.1',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.10.0',
 'vaex-server': '0.6.1',
 'vaex-astro': '0.9.0',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.14.0'}

Here is the error message.
```python
import vaex as vx
li = ['ah.1.arrow', 'ah.199.arrow', 'ah.79.arrow']
vdf = vx.from_arrays(fname = li)
vdf['fname'].str.rsplit('.',2)

Traceback (most recent call last):

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))

KeyError: 'Unknown variables or column: "str_rsplit(fname, \'.\', 2)"'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 2047, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, array_type=array_type, parallel=False)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 2895, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 6155, in _evaluate_implementation
    value = scope.evaluate(expression)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)

  File "<string>", line 1, in <module>

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/functions.py", line 47, in decorated
    return f(x, *args, **kwargs)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/functions.py", line 1925, in str_rsplit
    return pc.split_pattern(x, reverse=True, max_splits=max_splits)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/pyarrow/compute.py", line 189, in wrapper
    options = _handle_options(func_name, option_class, options,

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/pyarrow/compute.py", line 165, in _handle_options
    return option_class(**kwargs)

  File "pyarrow/_compute.pyx", line 1182, in pyarrow._compute.SplitPatternOptions.__init__

TypeError: __init__() takes exactly 2 positional arguments (1 given)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))

KeyError: 'Unknown variables or column: "str_rsplit(fname, \'.\', 2)"'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/IPython/core/formatters.py", line 702, in __call__
    printer.pretty(obj)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/IPython/lib/pretty.py", line 394, in pretty
    return _repr_pprint(obj, self, cycle)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/IPython/lib/pretty.py", line 700, in _repr_pprint
    output = repr(obj)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/expression.py", line 777, in __repr__
    return self._repr_plain_()

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/expression.py", line 807, in _repr_plain_
    dtype = self.dtype

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/expression.py", line 480, in dtype
    return self.df.data_type(self)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 2049, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, array_type=array_type, parallel=False)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 2895, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 6155, in _evaluate_implementation
    value = scope.evaluate(expression)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)

  File "<string>", line 1, in <module>

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/functions.py", line 47, in decorated
    return f(x, *args, **kwargs)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/functions.py", line 1925, in str_rsplit
    return pc.split_pattern(x, reverse=True, max_splits=max_splits)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/pyarrow/compute.py", line 189, in wrapper
    options = _handle_options(func_name, option_class, options,

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/pyarrow/compute.py", line 165, in _handle_options
    return option_class(**kwargs)

  File "pyarrow/_compute.pyx", line 1182, in pyarrow._compute.SplitPatternOptions.__init__

TypeError: __init__() takes exactly 2 positional arguments (1 given)
```

But it works with
`vdf['fname'].str.split('.',2)`

**Comment by JovanVeljanoski** [comment]
Ah yeah, indeed,, there is a bug in `rsplit` when a non-whitespace patterns is specified. I will fix it right away.

**Comment by JovanVeljanoski** [comment]
This was fixed via #1700 
Thanks for raising this!
