### ISSUE TITLE
Issue running vaex in PyCharm

### ISSUE THREAD

**Issue by cibic89** [vaexio/vaex#638]
Mine does this with this code in PyCharm 2019.3.3:
```
import pandas as pd
import numpy as np
import vaex
from IPython.display import display
from vaex.ml.sklearn import Predictor
import lightgbm
from sklearn import model_selection as skl_ms
import gc


#%%
# generate regression dataset
df_pd = pd.DataFrame(np.random.randint(2, size=(10**7, 100), dtype=np.uint8))
gc.collect()

df_pd.columns = [str(vname) for vname in list(df_pd.columns.values)]
target_vname = "target"
df_pd.rename(columns={"99": target_vname}, inplace=True, errors="ignore")
features = [vname for vname in list(df_pd.columns.values) if vname != target_vname]
df_pd_train, df_pd_test = skl_ms.train_test_split(df_pd, test_size=0.3, random_state=123)
df_vaex = vaex.from_pandas(df_pd)
df_vaex_train, df_vaex_test = df_vaex.ml.train_test_split(test_size=0.3, verbose=False)

#%%
date_time_fmt = "%Y/%m/%d %H:%M:%S"
start_time = pd.to_datetime("now")
print("Start time:", start_time.strftime(date_time_fmt))

booster = lightgbm.LGBMRegressor()  # <-- here!
# vaex_model = Predictor(model=booster, features=features, target=target_vname, prediction_name='pred')
# vaex_model.fit(df=df_vaex_train)
# df_train = vaex_model.transform(df_vaex_train)

finish_time = pd.to_datetime("now")
print("Finish time:", finish_time.strftime(date_time_fmt), "or", (finish_time-start_time).seconds//60, "minutes.")
```
**Output:**
```
Start time: 2020/03/08 21:01:34
Finish time: 2020/03/08 21:01:34 or 0 minutes.
ERROR:Thread-25:vaex:error evaluating: _ at rows 0-5
Traceback (most recent call last):
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5237, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 306, in map_reduce
    return self._delay(delay, task)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 1428, in _delay
    self.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 293, in execute
    self.executor.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
ERROR:Thread-25:vaex:error evaluating: _0 at rows 0-5
Traceback (most recent call last):
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5237, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 306, in map_reduce
    return self._delay(delay, task)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 1428, in _delay
    self.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 293, in execute
    self.executor.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
ERROR:Thread-25:vaex:error evaluating: _1 at rows 0-5
Traceback (most recent call last):
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5237, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 306, in map_reduce
    return self._delay(delay, task)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 1428, in _delay
    self.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 293, in execute
    self.executor.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
ERROR:Thread-25:vaex:error evaluating: _2 at rows 0-5
Traceback (most recent call last):
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5237, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 306, in map_reduce
    return self._delay(delay, task)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 1428, in _delay
    self.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 293, in execute
    self.executor.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
ERROR:Thread-25:vaex:error evaluating: _3 at rows 0-5
Traceback (most recent call last):
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5237, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 306, in map_reduce
    return self._delay(delay, task)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 1428, in _delay
    self.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 293, in execute
    self.executor.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
ERROR:Thread-25:vaex:error evaluating: _4 at rows 0-5
Traceback (most recent call last):
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5237, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 306, in map_reduce
    return self._delay(delay, task)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 1428, in _delay
    self.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 293, in execute
    self.executor.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
ERROR:Thread-25:vaex:error evaluating: _5 at rows 0-5
Traceback (most recent call last):
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5237, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 306, in map_reduce
    return self._delay(delay, task)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 1428, in _delay
    self.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 293, in execute
    self.executor.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
ERROR:Thread-25:vaex:error evaluating: _6 at rows 0-5
Traceback (most recent call last):
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5237, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 306, in map_reduce
    return self._delay(delay, task)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 1428, in _delay
    self.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 293, in execute
    self.executor.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
ERROR:Thread-25:vaex:error evaluating: _7 at rows 0-5
Traceback (most recent call last):
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5237, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 306, in map_reduce
    return self._delay(delay, task)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 1428, in _delay
    self.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 293, in execute
    self.executor.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
ERROR:Thread-25:vaex:error evaluating: _8 at rows 0-5
Traceback (most recent call last):
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5237, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 306, in map_reduce
    return self._delay(delay, task)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 1428, in _delay
    self.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 293, in execute
    self.executor.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
ERROR:Thread-25:vaex:error evaluating: _9 at rows 0-5
Traceback (most recent call last):
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5237, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 306, in map_reduce
    return self._delay(delay, task)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 1428, in _delay
    self.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 293, in execute
    self.executor.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
ERROR:Thread-25:vaex:error evaluating: target at rows 0-5
Traceback (most recent call last):
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5237, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 306, in map_reduce
    return self._delay(delay, task)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 1428, in _delay
    self.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 293, in execute
    self.executor.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
ERROR:Thread-25:vaex:error evaluating: index at rows 0-5
Traceback (most recent call last):
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5237, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 306, in map_reduce
    return self._delay(delay, task)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 1428, in _delay
    self.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 293, in execute
    self.executor.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
ERROR:Thread-25:vaex:error evaluating: _ at rows 9999995-10000000
Traceback (most recent call last):
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 5237, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 306, in map_reduce
    return self._delay(delay, task)
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 1428, in _delay
    self.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\dataframe.py", line 293, in execute
    self.executor.execute()
  File " \User\Miniconda3\envs\vaex_vs_pd\lib\site-packages\vaex\execution.py", line 127, in execute
    raise RuntimeError("nested execute call")
RuntimeError: nested execute call
```

_Originally posted by @cibic89 in https://github.com/vaexio/vaex/issues/543#issuecomment-596251972_

**Comment by maartenbreddels** [comment]
I think this is fixed by #670

**Comment by xdssio** [comment]
I found a param under Preferences→Build, Execution, Deployment→ Console
Use existing console for "Show console variables by default".
Set it on solved my problem.

**Comment by cibic89** [comment]
the problem is not fixed when I use IPython kernel in PyCharm. It works like wonders in jupyter notebook/jupyter lab so happy to close this issue.
